---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3 # Number of pods
  selector:
    matchLabels:
      app: nginx
  template: # Pod template!
    metadata:
      labels:
        app: nginx
    spec: # Pod spec goes here
      containers:
      - name: nginx
        image: nginx:alpine-1.28
